import time
import keyboard
import pyautogui
while True:
    print("Ведите пароль:")
    par=input("")
    if par=="Ёлки иголки":
       print("Доступ разрешён.")
       time.sleep(0.2)
       print("Добро пожаловать")
       time.sleep(1)
       print("-А на каком я сайте?")
       time.sleep(1)
       print("Por...")
       time.sleep(1)
       print("-Я понел.")
       time.sleep(1)
       print("*Выход*")
       time.sleep(1)
    elif par=="Лололошка топ":
        time.sleep(1)
        print("Это да, но это не пароль")
        time.sleep(1)
        print("Доступ отклонён")
        time.sleep(1)
    if par=="Я незнаю":
        time.sleep(1)
        print("Блин я теперь забыл его(")
        time.sleep(1)
    elif par=="Смешарики топ":
        time.sleep(1)
        print("Согласен тебе разрешён доступ.")
        time.sleep(1)
        print("Добро пожаловать")
        time.sleep(1)
    if par=="Снег":
        time.sleep(1)
        print("...")
        time.sleep(1)
        print("Неа лёд")
        time.sleep(1)
        print("Доступ отклонён")
        time.sleep(1)
    elif par=="Скибиди доп ес":
        time.sleep(1)
        print("Туалет, чтоли?")
        time.sleep(1)
        print("Ща камеру достану")
        time.sleep(1)
        print("Доступ отклонён")
        time.sleep(1)
    if par=="Новогодняя песня":
        print("Окей ща будет")
        pyautogui.moveTo(1750,5)
        time.sleep(1)
        pyautogui.click(button="left")
        time.sleep(1)
        pyautogui.moveTo(10,900)
        time.sleep(1)
        pyautogui.doubleClick()
        time.sleep(1)
        keyboard.write("https://www.youtube.com/watch?v=DWG74q_LjLs")
        pyautogui.press("enter")
    elif par=="Подсказку дай":
        time.sleep(1)
        print("Окей Абоба:")
        time.sleep(1)
        print("Знаменитая фраза Кроша из смешариков. P.S. Ты меня не     слышал")
        time.sleep(1)
    if par=="А какой сайт":
        time.sleep(1)
        print("18+ На P начинается")
        time.sleep(1)
        print("На b заканчивается")
        time.sleep(1)
        print("А в чём вопрос?")
        time.sleep(1)
        u=input("-")
        if u=="Да так просто интересно":
            print("ПОН")
            time.sleep(1)
        elif u=="Не в чём":
            print("Ну тогда")
            time.sleep(1)
            print("Доступ отклонён")
            time.sleep(1)
        else:
            time.sleep(1)
            print("Не понел так, что")
            time.sleep(1)
            print("Доступ оклонён")
            time.sleep(1)